GET http://localhost:3003/api/blogs
Content-Type: application/json

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VydHdvIiwiaWQiOiI2N2E2MjMzOGJlYWYzZTg0ZjY1Mjc5ZjYiLCJpYXQiOjE3Mzg5NDcxNjZ9.SCp1DjEp0SgRzWZoSwy4bCSo1q_VnAgyE88k9_NwQ0I

{
  "title": "Test blog with valid auth",
  "author": "Tester",
  "url": "example.org",
  "likes": 10  
}

###

GET http://localhost:3003/api/users
Content-Type: application/json

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testusertwo",
  "name": "Tester",
  "password": "secret password2"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "testusertwo",
  "password": "secret password2"
}
