GET http://localhost:3003/api/blogs
Content-Type: application/json

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test blog",
  "author": "Tester",
  "url": "example.org",
  "likes": 10  
}