GET http://localhost:3003/api/blogs
Content-Type: application/json

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test blog",
  "author": "Tester",
  "url": "example.org",
  "likes": 10  
}

###

GET http://localhost:3003/api/users
Content-Type: application/json

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testusertwo",
  "name": "Tester",
  "password": "secret password2"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "testusertwo",
  "password": "secret password2"
}
